// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNyQJwodHP80j-CB_QBJRya-XtBk3RPrE',
    appId: '1:203732561607:web:a65c44fdf16e711da818e2',
    messagingSenderId: '203732561607',
    projectId: 'fir-email-pw-login',
    authDomain: 'fir-email-pw-login.firebaseapp.com',
    storageBucket: 'fir-email-pw-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUTdiIK1RiaEWH7ItRXx9OpqisjUcsZAs',
    appId: '1:203732561607:android:0ef02174cef4a86ca818e2',
    messagingSenderId: '203732561607',
    projectId: 'fir-email-pw-login',
    storageBucket: 'fir-email-pw-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdqYisNHBWzY5VPmh1iJB7hzYNOx8Vm8',
    appId: '1:203732561607:ios:86294b1b883b0f3ea818e2',
    messagingSenderId: '203732561607',
    projectId: 'fir-email-pw-login',
    storageBucket: 'fir-email-pw-login.appspot.com',
    iosClientId: '203732561607-oe32j1rlgn2kdf5qekqm421u920d1jsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEmailPwLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZdqYisNHBWzY5VPmh1iJB7hzYNOx8Vm8',
    appId: '1:203732561607:ios:c33800e93aa74d66a818e2',
    messagingSenderId: '203732561607',
    projectId: 'fir-email-pw-login',
    storageBucket: 'fir-email-pw-login.appspot.com',
    iosClientId: '203732561607-7jlr186ijomj7bjcpm1ilqhva4sq7jdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEmailPwLogin.RunnerTests',
  );
}
